<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.tasks</groupId>
    <artifactId>AdvancedMultithreading</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>AdvancedMultithreading</name>
    <url>http://maven.apache.org</url>
    <modules>
        <module>Task 2 - Multithreading Sorting via FJP</module>
        <module>Task 3 - File Scanner via FJP</module>
        <module>Task 4 - Completable Future</module>
        <module>Task 5 Producer and consumers</module>
        <module>Task 6</module>
        <module>Task 7</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
